In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [20]:
sent = [
       "Cute White Rabbit is playing in green fields in front of Big Green Gate ",
       "Big Brown Dog chases rabbit in GREEN Fields",
       "White rabbit ran into Big Green Gate to escape from Big Brown Dog",
    "Big Brown Dog jump over Big Green Gate to catch white RABBIT"
]

In [21]:
sent

['Cute White Rabbit is playing in green fields in front of Big Green Gate ',
 'Big Brown Dog chases rabbit in GREEN Fields',
 'White rabbit ran into Big Green Gate to escape from Big Brown Dog',
 'Big Brown Dog jump over Big Green Gate to catch white RABBIT']

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
cvec=CountVectorizer()

In [24]:
cvec

CountVectorizer()

In [25]:
cvec.fit(sent)

CountVectorizer()

In [26]:
cvec.get_feature_names_out()

array(['big', 'brown', 'catch', 'chases', 'cute', 'dog', 'escape',
       'fields', 'from', 'front', 'gate', 'green', 'in', 'into', 'is',
       'jump', 'of', 'over', 'playing', 'rabbit', 'ran', 'to', 'white'],
      dtype=object)

In [27]:
cvec.vocabulary_

{'cute': 4,
 'white': 22,
 'rabbit': 19,
 'is': 14,
 'playing': 18,
 'in': 12,
 'green': 11,
 'fields': 7,
 'front': 9,
 'of': 16,
 'big': 0,
 'gate': 10,
 'brown': 1,
 'dog': 5,
 'chases': 3,
 'ran': 20,
 'into': 13,
 'to': 21,
 'escape': 6,
 'from': 8,
 'jump': 15,
 'over': 17,
 'catch': 2}

In [28]:
cvec.transform(sent) # spare means more number of zeros in the sentences

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 43 stored elements and shape (4, 23)>

In [29]:
cvec.transform(sent).toarray()

array([[1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 0, 1, 0, 1, 0, 1, 1, 0, 0,
        1],
       [1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0],
       [2, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
        1],
       [2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        1]])

In [30]:
ary=cvec.transform(sent).toarray()

In [31]:
ary

array([[1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 0, 1, 0, 1, 0, 1, 1, 0, 0,
        1],
       [1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0],
       [2, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
        1],
       [2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        1]])

In [32]:
pd.DataFrame(ary)

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,1,0,0,0,1,0,0,1,0,1,...,0,1,0,1,0,1,1,0,0,1
1,1,1,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2,2,1,0,0,0,1,1,0,1,0,...,1,0,0,0,0,0,1,1,1,1
3,2,1,1,0,0,1,0,0,0,0,...,0,0,1,0,1,0,1,0,1,1

In [33]:
cols=['big', 'brown', 'catch', 'chases', 'cute', 'dog', 'escape',
       'fields', 'from', 'front', 'gate', 'green', 'in', 'into', 'is',
       'jump', 'of', 'over', 'playing', 'rabbit', 'ran', 'to', 'white']

In [34]:
pd.DataFrame(ary,columns=cols)

,big,brown,catch,chases,cute,dog,escape,fields,from,front,...,into,is,jump,of,over,playing,rabbit,ran,to,white
0,1,0,0,0,1,0,0,1,0,1,...,0,1,0,1,0,1,1,0,0,1
1,1,1,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2,2,1,0,0,0,1,1,0,1,0,...,1,0,0,0,0,0,1,1,1,1
3,2,1,1,0,0,1,0,0,0,0,...,0,0,1,0,1,0,1,0,1,1

## TFIDF

In [35]:
sent

['Cute White Rabbit is playing in green fields in front of Big Green Gate ',
 'Big Brown Dog chases rabbit in GREEN Fields',
 'White rabbit ran into Big Green Gate to escape from Big Brown Dog',
 'Big Brown Dog jump over Big Green Gate to catch white RABBIT']

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tfvec=TfidfVectorizer()

In [38]:
tfvec

TfidfVectorizer()

In [39]:
tfvec.fit(sent)

TfidfVectorizer()

In [40]:
tfvec.get_feature_names_out()

array(['big', 'brown', 'catch', 'chases', 'cute', 'dog', 'escape',
       'fields', 'from', 'front', 'gate', 'green', 'in', 'into', 'is',
       'jump', 'of', 'over', 'playing', 'rabbit', 'ran', 'to', 'white'],
      dtype=object)

In [41]:
len(tfvec.get_feature_names_out())

23

In [42]:
tfvec.vocabulary_

{'cute': 4,
 'white': 22,
 'rabbit': 19,
 'is': 14,
 'playing': 18,
 'in': 12,
 'green': 11,
 'fields': 7,
 'front': 9,
 'of': 16,
 'big': 0,
 'gate': 10,
 'brown': 1,
 'dog': 5,
 'chases': 3,
 'ran': 20,
 'into': 13,
 'to': 21,
 'escape': 6,
 'from': 8,
 'jump': 15,
 'over': 17,
 'catch': 2}

In [43]:
tfvec.transform(sent)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 43 stored elements and shape (4, 23)>

In [44]:
tfvec.transform(sent).toarray()

array([[0.16061075, 0.        , 0.        , 0.        , 0.30777689,
        0.        , 0.        , 0.24265484, 0.        , 0.30777689,
        0.19645   , 0.3212215 , 0.48530967, 0.        , 0.30777689,
        0.        , 0.30777689, 0.        , 0.30777689, 0.16061075,
        0.        , 0.        , 0.19645   ],
       [0.26509705, 0.32425175, 0.        , 0.50800302, 0.        ,
        0.32425175, 0.        , 0.40051542, 0.        , 0.        ,
        0.        , 0.26509705, 0.40051542, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.26509705,
        0.        , 0.        , 0.        ],
       [0.37167534, 0.22730615, 0.        , 0.        , 0.        ,
        0.22730615, 0.356119  , 0.        , 0.356119  , 0.        ,
        0.22730615, 0.18583767, 0.        , 0.356119  , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.18583767,
        0.356119  , 0.28076831, 0.22730615],
       [0.3977517 , 0.24325371, 0.38110395, 0.        , 0.        ,
        0.24325371, 0.        , 0.        , 0.        , 0.        ,
        0.24325371, 0.19887585, 0.        , 0.        , 0.        ,
        0.38110395, 0.        , 0.38110395, 0.        , 0.19887585,
        0.        , 0.30046673, 0.24325371]])